CREATE SCHEMA IF NOT EXISTS public;

CREATE TABLE IF NOT EXISTS public.users (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username text NOT NULL UNIQUE,
    password_hash text NOT NULL,
    theme text NOT NULL DEFAULT 'auto',
    created_at timestamp without time zone DEFAULT now(),
    language text NOT NULL DEFAULT 'en',
    first_name text,
    last_name text,
    role text NOT NULL DEFAULT 'user',
    last_login timestamp with time zone,
    password_needs_reset boolean NOT NULL DEFAULT false
);

CREATE TABLE IF NOT EXISTS public.app_config (
    key text PRIMARY KEY,
    value text NOT NULL
);

CREATE TABLE IF NOT EXISTS public.mailing_lists (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL,
    address text NOT NULL UNIQUE,
    is_active boolean NOT NULL DEFAULT true,
    subject_tag text,
    imap_user text,
    imap_pass text,
    smtp_user text,
    smtp_pass text,
    open_posting boolean DEFAULT true,
    imap_host text,
    imap_port integer DEFAULT 993,
    smtp_host text,
    smtp_port integer DEFAULT 465,
    imap_folder text DEFAULT 'INBOX'
);

CREATE TABLE IF NOT EXISTS public.list_members (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email text NOT NULL,
    display_name text,
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    list_id integer REFERENCES public.mailing_lists(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_list_members_active
    ON public.list_members (is_active);

CREATE INDEX IF NOT EXISTS idx_list_members_list_id
    ON public.list_members (list_id);

CREATE UNIQUE INDEX IF NOT EXISTS uq_list_members_list_email
    ON public.list_members (list_id, lower(email));
